server {
  host = "0.0.0.0"
  host = ${?SERVER_HOST}
  port = 8080
  port = ${?SERVER_PORT}
}

admin {
  username = ${ADMIN_USERNAME}
  password = ${ADMIN_PASSWORD}
}

database {
  driver = "org.postgresql.Driver"
  url = "jdbc:postgresql://localhost:5432/cwfgw"
  url = ${?DATABASE_URL}
  user = "cwfgw"
  user = ${?DATABASE_USER}
  password = "cwfgw"
  password = ${?DATABASE_PASSWORD}
  pool-size = 10
}
